In [2]:
import pandas as pd
import os
import re
import scipy

In [3]:
data_dir='../../srndna-data/stimuli/psychopy/logs'
subs=[p for p in os.listdir(data_dir) if p.startswith(('1','2'))]

f_list=[]
for sub in subs:
    f_list= f_list+[data_dir+"/%s/"%(sub)+f for f in os.listdir(data_dir+"/%s"%(sub)) if 'ultimatum' in f]

df_list=[]
for f in f_list:
    sub=re.search('logs/(.*)/',f).group(1)
    tmp=pd.read_csv(f)
    if len(tmp[tmp['Partner']=='Partner'])>0:
        x=tmp[tmp['Partner']=='Partner'].index[-1]
        tmp=pd.read_csv(f,skiprows=x)

    tmp['sub']=sub
    df_list.append(tmp)
df=pd.concat(df_list)
df.reset_index(inplace=True)
df=df[['sub','Partner','Offer','resp']]
df=df.rename(columns={'sub':"subjID",
                     "Offer":"offer",
                     "resp":"accept"})
df['accept']=pd.to_numeric(df['accept'])-2
df=df[df['accept']<=900]
df.dropna(inplace=True)
display(df.head())
for column in df.columns:
    print ("Unique values for  "+column+":",df[column].unique())

  subjID  Partner  offer  accept
1    217      3.0    2.0     0.0
2    217      3.0    2.0     0.0
3    217      3.0    3.0     0.0
4    217      3.0    2.0     0.0
5    217      3.0    8.0     1.0

Unique values for  subjID: ['217' '129' '231' '149' '234' '256' '255' '152' '239' '228' '137' '130'
 '103' '153' '204' '155' '150' '247' '221' '258' '159' '124' '209' '118'
 '105' '158' '238' '227' '220' '215' '156' '236' '114' '136' '249' '253'
 '115' '106' '211' '113' '207' '101' '230' '250' '212' '216' '125' '126'
 '134' '257' '138' '154' '240' '110' '208' '235' '133' '254' '104' '120'
 '224' '225' '112' '223' '241' '259' '107' '242' '252' '151' '128' '246'
 '102' '237' '147' '210' '157' '218' '243' '111' '206' '251' '116' '131'
 '142' '121' '205' '132' '233' '226' '140' '117' '135' '127' '108' '222'
 '122' '141' '145' '245' '109' '213']
Unique values for  Partner: [3. 2. 1.]
Unique values for  offer: [ 2.  3.  8.  6.  1.  9. 10.  4.  7.  5.]
Unique values for  accept: [0. 1.]

In [4]:
df1=df[df['Partner']==1].copy()
df2=df[df['Partner']==2].copy()
df3=df[df['Partner']==3].copy()
df4=[]
display(df1)
for tmp in [df1,df2,df3]:
    display()
    tmp['subjID']=tmp['subjID']+'_'+tmp['Partner'].astype(int).astype(str)
    df4.append(tmp)
    
df4=pd.concat(df4)
df4['subjID'].unique()

      subjID  Partner  offer  accept
24       217      1.0    4.0     0.0
25       217      1.0    6.0     0.0
26       217      1.0    7.0     1.0
27       217      1.0    8.0     1.0
28       217      1.0    7.0     1.0
...      ...      ...    ...     ...
14952    213      1.0    3.0     0.0
14953    213      1.0    2.0     0.0
14954    213      1.0    4.0     0.0
14955    213      1.0    2.0     0.0
14956    213      1.0    9.0     1.0

[4769 rows x 4 columns]

array(['217_1', '129_1', '231_1', '149_1', '234_1', '256_1', '255_1',
       '152_1', '239_1', '228_1', '137_1', '130_1', '103_1', '153_1',
       '204_1', '155_1', '150_1', '247_1', '221_1', '258_1', '159_1',
       '124_1', '209_1', '118_1', '105_1', '158_1', '238_1', '227_1',
       '220_1', '215_1', '156_1', '236_1', '114_1', '136_1', '249_1',
       '253_1', '115_1', '106_1', '211_1', '113_1', '207_1', '101_1',
       '230_1', '250_1', '212_1', '216_1', '125_1', '126_1', '134_1',
       '257_1', '138_1', '154_1', '240_1', '110_1', '208_1', '235_1',
       '133_1', '254_1', '104_1', '120_1', '224_1', '225_1', '112_1',
       '223_1', '241_1', '259_1', '107_1', '242_1', '252_1', '151_1',
       '128_1', '246_1', '102_1', '237_1', '147_1', '210_1', '157_1',
       '218_1', '243_1', '111_1', '206_1', '251_1', '116_1', '131_1',
       '142_1', '121_1', '205_1', '132_1', '233_1', '226_1', '140_1',
       '117_1', '135_1', '127_1', '108_1', '222_1', '122_1', '141_1',
       '145_1', '245_1', '109_1', '213_1', '217_2', '129_2', '231_2',
       '149_2', '234_2', '256_2', '255_2', '152_2', '239_2', '228_2',
       '137_2', '130_2', '103_2', '153_2', '204_2', '155_2', '150_2',
       '247_2', '221_2', '258_2', '159_2', '124_2', '209_2', '118_2',
       '105_2', '158_2', '238_2', '227_2', '220_2', '215_2', '156_2',
       '236_2', '114_2', '136_2', '249_2', '253_2', '115_2', '106_2',
       '211_2', '113_2', '207_2', '101_2', '230_2', '250_2', '212_2',
       '216_2', '125_2', '126_2', '134_2', '257_2', '138_2', '154_2',
       '240_2', '110_2', '208_2', '235_2', '133_2', '254_2', '104_2',
       '120_2', '224_2', '225_2', '112_2', '223_2', '241_2', '259_2',
       '107_2', '242_2', '252_2', '151_2', '128_2', '246_2', '102_2',
       '237_2', '147_2', '210_2', '157_2', '218_2', '243_2', '111_2',
       '206_2', '251_2', '116_2', '131_2', '142_2', '121_2', '205_2',
       '132_2', '233_2', '226_2', '140_2', '117_2', '135_2', '127_2',
       '108_2', '222_2', '122_2', '141_2', '145_2', '245_2', '109_2',
       '213_2', '217_3', '129_3', '231_3', '149_3', '234_3', '256_3',
       '255_3', '152_3', '239_3', '228_3', '137_3', '130_3', '103_3',
       '153_3', '204_3', '155_3', '150_3', '247_3', '221_3', '258_3',
       '159_3', '124_3', '209_3', '118_3', '105_3', '158_3', '238_3',
       '227_3', '220_3', '215_3', '156_3', '236_3', '114_3', '136_3',
       '249_3', '253_3', '115_3', '106_3', '211_3', '113_3', '207_3',
       '101_3', '230_3', '250_3', '212_3', '216_3', '125_3', '126_3',
       '134_3', '257_3', '138_3', '154_3', '240_3', '110_3', '208_3',
       '235_3', '133_3', '254_3', '104_3', '120_3', '224_3', '225_3',
       '112_3', '223_3', '241_3', '259_3', '107_3', '242_3', '252_3',
       '151_3', '128_3', '246_3', '102_3', '237_3', '147_3', '210_3',
       '157_3', '218_3', '243_3', '111_3', '206_3', '251_3', '116_3',
       '131_3', '142_3', '121_3', '205_3', '132_3', '233_3', '226_3',
       '140_3', '117_3', '135_3', '127_3', '108_3', '222_3', '122_3',
       '141_3', '145_3', '245_3', '109_3', '213_3'], dtype=object)

In [5]:
from hbayesdm.diagnostics import rhat, print_fit, hdi, plot_hdi, extract_ic
from hbayesdm.models import ug_delta, ug_bayes

output1=ug_delta(data=df1,niter=2000,nwarmup=1000,nchain=10,ncore=6)

INFO:pystan:COMPILING THE C++ CODE FOR MODEL ug_delta_ccb98c63d1edecad05e5200ddc3e04ad NOW.
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /opt/anaconda3/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1948,
                 from /opt/anaconda3/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /opt/anaconda3/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /tmp/pystan_ft1m2g9l/stanfit4ug_delta_ccb98c63d1edecad05e5200ddc3e04ad_6451472543507137836.cpp:836:
/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
In file included from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat/prob/poisson_log_glm_log.hpp:5,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat.hpp:336,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/src/stan/io/dump.hpp:6,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/py_var_context.hpp:12,
                 from /tmp/pystan_ft1m2g9l/stanfit4ug_delta_ccb98c63d1edecad05e5200ddc3e04ad_6451472543507137836.cpp:845:
/opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat/prob/poisson_log_glm_lpmf.hpp: In function ‘typename stan::return_type<T_x, T_alpha, T_beta>::type stan::math::poisson_log_glm_lpmf(const T_y&, const T_x&, const T_alpha&, const T_beta&)’:
/opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat/prob/poisson_log_glm_lpmf.hpp:64:59: warning: typedef ‘T_alpha_val’ locally defined but not used [-Wunused-local-typedefs]
   64 |       typename partials_return_type<T_alpha>::type>::type T_alpha_val;
      |                                                           ^~~~~~~~~~~
In file included from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0/boost/numeric/ublas/matrix.hpp:19,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0/boost/numeric/odeint/util/ublas_wrapper.hpp:24,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0/boost/numeric/odeint.hpp:25,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/arr/functor/integrate_ode_rk45.hpp:17,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/arr.hpp:46,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat.hpp:344,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/src/stan/io/dump.hpp:6,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/py_var_context.hpp:12,
                 from /tmp/pystan_ft1m2g9l/stanfit4ug_delta_ccb98c63d1edecad05e5200ddc3e04ad_6451472543507137836.cpp:845:
/opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0/boost/numeric/ublas/matrix_expression.hpp: In member function ‘void boost::numeric::ublas::matrix_binary<E1, E2, F>::const_iterator1::increment(boost::numeric::ublas::sparse_bidirectional_iterator_tag)’:
/opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0/boost/numeric/ublas/matrix_expression.hpp:2224:17: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
 2224 |                 if (it2_ != it2_end_)
      |                 ^~
/opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0/boost/numeric/ublas/matrix_expression.hpp:2227:21: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
 2227 |                     if (it2_ != it2_end_) {
      |                     ^~
In file included from /tmp/pystan_ft1m2g9l/stanfit4ug_delta_ccb98c63d1edecad05e5200ddc3e04ad_6451472543507137836.cpp:846:
/opt/anaconda3/lib/python3.8/site-packages/pystan/stan_fit.hpp: In function ‘int pystan::{anonymous}::command(pystan::StanArgs&, Model&, pystan::StanHolder&, const std::vector<long unsigned int>&, const std::vector<std::__cxx11::basic_string<char> >&, RNG_t&)’:
/opt/anaconda3/lib/python3.8/site-packages/pystan/stan_fit.hpp:841:12: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
  841 |       std::auto_ptr<stan::io::var_context> init_context_ptr;
      |            ^~~~~~~~
In file included from /usr/include/c++/9/memory:80,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0/boost/config/no_tr1/memory.hpp:21,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0/boost/smart_ptr/shared_ptr.hpp:23,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0/boost/shared_ptr.hpp:17,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat/fun/LDLT_factor.hpp:7,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat/err/check_ldlt_factor.hpp:6,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat.hpp:34,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/stan/src/stan/io/dump.hpp:6,
                 from /opt/anaconda3/lib/python3.8/site-packages/pystan/py_var_context.hpp:12,
                 from /tmp/pystan_ft1m2g9l/stanfit4ug_delta_ccb98c63d1edecad05e5200ddc3e04ad_6451472543507137836.cpp:845:
/usr/include/c++/9/bits/unique_ptr.h:53:28: note: declared here
   53 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
In file included from /tmp/pystan_ft1m2g9l/stanfit4ug_delta_ccb98c63d1edecad05e5200ddc3e04ad_6451472543507137836.cpp:848:
/tmp/pystan_ft1m2g9l/ug_delta_ccb98c63d1edecad05e5200ddc3e04ad.hpp: In member function ‘void ug_delta_ccb98c63d1edecad05e5200ddc3e04ad_namespace::ug_delta_ccb98c63d1edecad05e5200ddc3e04ad::transform_inits(const stan::io::var_context&, std::vector<int>&, std::vector<double>&, std::ostream*) const’:
/tmp/pystan_ft1m2g9l/ug_delta_ccb98c63d1edecad05e5200ddc3e04ad.hpp:180:24: warning: typedef ‘local_scalar_t__’ locally defined but not used [-Wunused-local-typedefs]
  180 |         typedef double local_scalar_t__;
      |                        ^~~~~~~~~~~~~~~~
/tmp/pystan_ft1m2g9l/stanfit4ug_delta_ccb98c63d1edecad05e5200ddc3e04ad_6451472543507137836.cpp: In function ‘PyObject* __pyx_pf_69stanfit4ug_delta_ccb98c63d1edecad05e5200ddc3e04ad_6451472543507137836_2_call_sampler(PyObject*, PyObject*, PyObject*, PyObject*)’:
/tmp/pystan_ft1m2g9l/stanfit4ug_delta_ccb98c63d1edecad05e5200ddc3e04ad_6451472543507137836.cpp:9617:30: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
 9617 |     __pyx_t_12 = ((__pyx_t_9 != __pyx_v_fitptr->param_names_oi().size()) != 0);
      |                    ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

KeyboardInterrupt:

In [ ]:
output2=ug_delta(data=df2,niter=2000,nwarmup=1000,nchain=10,ncore=6)

In [ ]:
output3=ug_delta(data=df3,niter=2000,nwarmup=1000,nchain=10,ncore=6)

In [ ]:
output4=ug_delta(data=df4,niter=2000,nwarmup=1000,nchain=10,ncore=6)

# Partner 1
- Over all looks good.
- Rhat all 1.01 or less
- Traces all converge more or less, no drift, though an occasional but expected extreme value.
- Additional note that about 2.5% of the mu_alpha posterior is greater than 1

In [ ]:
import numpy as np
np.sum(output1.par_vals['mu_alpha']>1)/len(output1.par_vals['mu_alpha'])

In [ ]:
import matplotlib.pyplot as plt
output1.plot('trace')
plt.show()
display(output1.fit)

# Partner 2
- Rhat for mu_aplha is 1.02 suggesting some notable non-convergence.
- This can be seen a little in the chain

In [ ]:
output2.plot('trace')
plt.show()
display(output2.fit)

# Partner 3
- Rhat below or at 1.01

In [ ]:
output3.plot('trace')
plt.show()
display(output3.fit)

# Output4

# Maybe worry about later
- Many individuals have wide posteriors for alpha and tau
- A wide posterior indicates large uncertainty in their individual estimates

In [ ]:
output1.plot_ind()

# Condition effects on parameters
- Generally no effect of condition on learning rate overall
## Partner 1 vs 2

In [ ]:
for val in output1.par_vals:
    if val.startswith('mu_'):
        alpha_diff12=output1.par_vals[val]-output2.par_vals[val]
        display(hdi(alpha_diff12))  # Compute the 95% Highest Density Interval (HDI).
        #plot_hdi( alpha_diff12 )    # plot the group mean differences

## Partner 1 vs 3

In [ ]:
for val in output1.par_vals:
    if val.startswith('mu_'):
        alpha_diff12=output1.par_vals[val]-output3.par_vals[val]
        display(hdi(alpha_diff12))  # Compute the 95% Highest Density Interval (HDI).
        #plot_hdi( alpha_diff12 )    # plot the group mean differences

## Partner 2 vs 3

In [ ]:
for val in output1.par_vals:
    if val.startswith('mu_'):
        alpha_diff12=output2.par_vals[val]-output3.par_vals[val]
        display(hdi(alpha_diff12))  # Compute the 95% Highest Density Interval (HDI).
        #plot_hdi( alpha_diff12 )    # plot the group mean differences

In [ ]:
res_df1=[]
res_df1=output1.all_ind_pars.reset_index().rename(columns={'index':'participant_id'})
res_df1['participant_id']='sub-'+res_df1['participant_id']

res_df2=[]
res_df2=output2.all_ind_pars.reset_index().rename(columns={'index':'participant_id'})
res_df2['participant_id']='sub-'+res_df2['participant_id']

res_df3=[]
res_df3=output3.all_ind_pars.reset_index().rename(columns={'index':'participant_id'})
res_df3['participant_id']='sub-'+res_df3['participant_id']

res_df=res_df1.merge(res_df2,on='participant_id',suffixes=('_1','_2'))
res_df=res_df.merge(res_df3,on='participant_id',suffixes=('_3'))

In [ ]:
ages=pd.read_csv('../../srndna-data/bids/participants.tsv',sep='\t')
display(res_df.head())
display(ages.head())

In [ ]:
res_df=res_df.merge(ages,on='participant_id')
display(res_df.head())
res_df['ep_diff']=res_df['ep_1']-res_df['ep_2']
res_df.to_csv('../derivatives/delat_values.csv',index=False)

In [ ]:
import seaborn as sms
import matplotlib.pyplot as plt
from statsmodels.formula.api import ols
import numpy as np
#from statsmodels.api.stats import anoval_lm
res_df['Old']=res_df['age']>50
for item in res_df.columns:
    if any(x in item for x in ['alpha','tau','ep']): 
        plt_df=res_df.copy()
        #plt_df[item]=np.sqrt(plt_df[item])
        #plt_df=plt_df[plt_df[item]<=2.5]
        res=ols('%s~Old'%(item),data=plt_df).fit()
        display(res.summary())
        #sms.catplot(x='Old',y=item,data=plt_df,kind='bar',dodge=True,hue='sex',ci=68)
        sms.catplot(x='Old',y=item,data=plt_df,kind='bar',dodge=True,ci=68)
        plt.show()

In [ ]:
P1_df=df[df['Partner']==1]
P2_df=df[df['Partner']==2]
P3_df=df[df['Partner']==3]


P1res=ug_delta(data=P1_df,niter=2000,nwarmup=1000,nchain=10,ncore=10)
P2res=ug_delta(data=P2_df,niter=2000,nwarmup=1000,nchain=10,ncore=10)
P3res=ug_delta(data=P3_df,niter=2000,nwarmup=1000,nchain=10,ncore=10)

In [ ]:
P1res.plot('trace')
P2res.plot('trace')
P3res.plot('trace')